### ISSUE TITLE
When running workflow tasks, add sorting rules to the service list

### ISSUE THREAD

**Issue by leozhang2018** [koderover/zadig-portal#6]
/kind enhancement

![image](https://user-images.githubusercontent.com/6907296/125546398-69513355-1a88-4592-a22c-3093382cf28d.png)

**Is your enhancement proposal related to a problem? Please describe.**
The current service list is out of order and it is not convenient to search

**Describe the solution you'd like**
Added sorting rules by first letter

**Comment by facethesunsea** [comment]
https://github.com/koderover/zadig-portal/pull/12
