### ISSUE TITLE
failed while 'yarn run dev', webpack dev server error

### ISSUE THREAD

**Issue by delai** [koderover/zadig-portal#683]
/kind bug

### What steps did you take and what happened:
1. failed while run `yarn run dev`, with error message:

```
➜  zadig-portal git:(main) yarn run dev
yarn run v1.22.17
$ webpack-dev-server --inline --progress --config build/webpack.dev.conf.js
(node:93444) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
 10% building modules 1/1 modules 0 activeTypeError: **Cannot read properties of undefined (reading 'upgrade')**
    at Server.<anonymous> (/Users/delai/koderover/zadig-portal/node_modules/webpack-dev-server/lib/Server.js:510:45)
    at Array.forEach (<anonymous>)
    at new Server (/Users/delai/koderover/zadig-portal/node_modules/webpack-dev-server/lib/Server.js:509:20)
    at startDevServer (/Users/delai/koderover/zadig-portal/node_modules/webpack-dev-server/bin/webpack-dev-server.js:386:14)
    at processOptions (/Users/delai/koderover/zadig-portal/node_modules/webpack-dev-server/bin/webpack-dev-server.js:350:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
✨  Done in 0.89s.
```

2. it looks like there is a bug in `webpack-dev-server/lib/Server.js`
```
  websocketProxies.forEach(function (wsProxy) {   // wsProxy is undefined here
    this.listeningApp.on('upgrade', wsProxy.upgrade);
  }, this);
```
so, in `webpack-dev-server/lib/Server.js`, if change 
```
          proxyMiddleware = getProxyMiddleware(proxyConfig);
          if (proxyConfig.ws) {
            websocketProxies.push(proxyMiddleware);
          }
```
to 
```
          proxyMiddleware = getProxyMiddleware(proxyConfig);
          if (proxyMiddleware && proxyConfig.ws) {
            websocketProxies.push(proxyMiddleware);
          }
```
or just comment out `ws: true,` in `zadig-portal/config/index.js`, then the project can **run normally** by `yarn run dev`

Am I the only one having this problem?

### Environment:
Node Version: v14.19.1 or v16.13.0

**Comment by leozhang2018** [comment]
Yes，it's a solution for this bug.

But the main reason is that the proxy `target` is empty.

When proxy target is undefined and ws is enabled，`yarn run dev` will be failed.

The backEndAddr should be set to the actual address of the zadig backend

![image](https://user-images.githubusercontent.com/6907296/162395758-88626048-4230-4b25-ac35-0e8bbaeff01f.png)

**Comment by delai** [comment]
thanks for reply!

I missed this information in doc.

But, after setting up my workflow in os.koderover.com and reading some docs, I still do not know how to get the backend address. However, this is another issue in Zadig Project.
