### ISSUE TITLE
There is only one system user, it should not be deleted

### ISSUE THREAD

**Issue by leozhang2018** [koderover/zadig-portal#7]
/kind enhancement

![image](https://user-images.githubusercontent.com/6907296/125546665-50f67bf6-372d-45b6-bc8b-50f136636c1c.png)

**Is your enhancement proposal related to a problem? Please describe.**
There is only one system user, it should not be deleted, otherwise you will not be able to log in

**Describe the solution you'd like**
Add delete condition, when there is a user, it cannot be deleted

**Comment by facethesunsea** [comment]
fix in #16
